[tool.poetry]
name = "ptorrent"
version = "0.1.0"
description = ""
authors = ["Anatoliy Platonov <p4m.dev@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
rich = "^9.5.1"
pytest = "^6.2.1"

[tool.poetry.dev-dependencies]
mypy = "^0.790"
black = "^20.8b1"
isort = "^5.6.4"
pre-commit = "^2.9.3"
flake8 = "^3.8.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
